- name: Installs SQL
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present
    update_cache: yes

- name: Create and edit the configuration file
  copy:
    content: |
      [mysqld]
      bind-address = 10.0.0.11

      default-storage-engine = innodb
      innodb_file_per_table = on
      max_connections = 4096
      collation-server = utf8_general_ci
      character-set-server = utf8
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    mode: "0755"

- name: Restart MariaDB service
  service:
    name: mysql
    state: restarted
    enabled: yes
