- name: Install ETCD
  apt:
    name: etcd
    state: present
    update_cache: yes

- name: Configuring the ETCD file
  copy:
    content: |
      ETCD_NAME="controller"
      ETCD_DATA_DIR="/var/lib/etcd"
      ETCD_INITIAL_CLUSTER_STATE="new"
      ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-01"
      ETCD_INITIAL_CLUSTER="controller=http://192.168.56.103:2380"
      ETCD_INITIAL_ADVERTISE_PEER_URLS="http://192.168.56.103:2380"
      ETCD_ADVERTISE_CLIENT_URLS="http://192.168.56.103:2379"
      ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS="http://192.168.56.103:2379"
    dest: /etc/default/etcd
    mode: "0777"

- name: Enable ETCD services
  service:
     name: etcd
     state: restarted
     enabled: true
