- name: Installing the Memcached
  apt:
    name:
      - memcached
      - python3-memcache
    state: present
    update_cache: yes

- name: Restart Memcached serivce
  service:
    name: memcached
    state: restarted
    enabled: yes
